[workspace]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "clinpgx-qa"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pydantic = ">=2.12.5,<3"
ruff = ">=0.14.14,<0.15"
loguru = ">=0.7.3,<0.8"
litellm = ">=1.81.7,<2"
